FROM nginx

ADD nginx.conf /etc/nginx/nginx.conf

COPY hshell/site /usr/share/nginx/html/hshell
COPY login/site /usr/share/nginx/html/login
COPY homescreen/site /usr/share/nginx/html/homescreen
COPY dev-config/site /usr/share/nginx/html/dev-config
COPY users/site /usr/share/nginx/html/users
